name: Release tagged revision

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: dotnet test Itp.HL7.sln
    - name: Build
      run: dotnet pack Itp.HL7.sln -c Release -p PackageOutputPath=${{github.workspace}}/dist
    - name: NugetPush
      run: dotnet nuget push -s https://api.nuget.org/v3/index.json --api-key ${{secrets.MG_NUGET_SECRET}} --skip-duplicate "${{github.workspace}}/dist/**/*.nupkg"